

CREATE TABLE brand(
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       brandName CHARACTER VARYING(64) NOT NULL,
                       country CHARACTER VARYING(64) NOT NULL
);

CREATE TABLE model (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       modelName CHARACTER VARYING(64) NOT NULL,
                       year_start BIGINT NOT NULL,
                       year_end BIGINT NOT NULL
);

CREATE TABLE position (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          brand CHARACTER VARYING(64) NOT NULL,
                          model CHARACTER VARYING(64) NOT NULL,
                          year_release BIGINT NOT NULL,
                          mileage BIGINT NOT NULL,
                          price BIGINT NOT NULL
);